apiVersion: v1
kind: Secret
metadata:
  name: database
data:
  MYSQL_DATABASE: {{ b64enc "db" }}
  MYSQL_HOST: {{  printf "%s-%s" .Values.name "service" | b64enc}}
  MYSQL_PASSWORD: {{ b64enc "admin" }}
  MYSQL_ROOT_PASSWORD: {{ b64enc "admin" }}
  MYSQL_USER: {{ b64enc "admin" }}
